### PR TITLE
Add Edge to wallet list

### PR DESCRIPTION
**Pull request by samholmes**
Edge is a non-custodial multi-currency wallet that supports the top cryptocurrencies and tokens including DOGE. Edge has established itself to be one of the longest standing self-custody solutions in addition to being fully an open-source. Source can be found on Edge's GitHub repo: https://github.com/EdgeApp/edge-react-gui

Edge Wallet is available as a mobile wallet (iOS & Android). More information can be found on the official website: https://edge.app

### CODE REVIEW

**Review by qlpqlp — COMMENTED** [review]
All good by me. Tested and semas to work fine :)

**Comment by samholmes** [comment]
@michilumin Any comments on this change?

**Comment by samholmes** [comment]
@michilumin Friendly ping

**Comment by samholmes** [comment]
@qlpqlp @michilumin can we get a quick review on this PR? It feels ready to merge. I'd sincerely appreciate it. Thanks!

**Comment by samholmes** [comment]
Is anyone alive out there?

**Comment by qlpqlp** [comment]
Sorry the late reply. Im tagging again to be reviewed asap 🙂

**Comment by samholmes** [comment]
Thanks for the bump, @qlpqlp 

I'll remain vigilant, persistent, and appreciative to getting this review finished and merged. 🙏

**Review by michilumin — APPROVED** [review]

**Pull request merged**
