### PR TITLE
'Dogecoin Inflation' Article

### PR DESCRIPTION
**Pull request by RichieJohn**

### CODE REVIEW

**Comment by AbcSxyZ** [comment]
Trick question: is Dogecoin deflationary ?

**Comment by RichieJohn** [comment]
Haha great question! 💯😉

**Comment by AbcSxyZ** [comment]
So, is Dogecoin deflationary ? Does it fit the following definition (from [Investopedia](https://www.investopedia.com/terms/d/deflation.asp)):

> Deflation is a general decline in prices for goods and services, typically associated with a contraction in the supply of money and credit in the economy. **During deflation, the purchasing power of currency rises over time.**

Alternatively, from [Wikipedia](https://en.wikipedia.org/wiki/Deflation):

> This allows more goods and services to be bought than before with the same amount of currency.

**Review by MishaBoar — APPROVED** [review]

**Comment by AbcSxyZ** [comment]
The answer is yes. Dogecoin is a deflationary currency [when the price go up]. Economically speaking, inflation do not mean "increase of a currency supply". It's just poorly used by crypto bros.

**Pull request merged**
