### PR TITLE
Updated Dogecoin Core download links to latest version.

### PR DESCRIPTION
**Pull request by daank-c**
This update brings download links for `Dogecoin Core` in the wallet section of the website up to `version 1.14.7`. Links for all languages were updated as requested in the discussion of my previous PR #299. The changes were tested on my local machine using Hugo's extended version as described in the `doc/how-to-translate-website.md` of this repository.

### CODE REVIEW

**Comment by qlpqlp** [comment]
Hello :)

You forgot to also change on https://github.com/dogecoinfoundation/dogecoin.com/blob/c795990d4aec38b68590a0a7495bfacab5752152/content/en/wallets/DogecoinCore.md?plain=1#L7 also the version to the latest version on all languages, everything else seems good to be merged :)

If you can change it, please change it to be able to review and approve :)

Much thanks for all your contribution  :)

**Review by qlpqlp — APPROVED** [review]
All good :)

**Comment by qlpqlp** [comment]
> Ping @qlpqlp @tjstebbing

You can now merge :D

**Comment by qlpqlp** [comment]
Thanks @MishaBoar , sorry the late reply @daank-c

**Comment by VickyPascale** [comment]
****

**Pull request merged**
