### PR TITLE
Remove Forks references and leaving only Bitcoin Fork do to lack of confirmations

### PR DESCRIPTION
**Pull request by qlpqlp**
Original discussion here: https://github.com/dogecoinfoundation/dogecoin.com/pull/312

### CODE REVIEW

**Comment by CrypticDriver** [comment]
@crabbyman825 Cringe

**Comment by crabbyman825** [comment]
> > Please for the love of god do not get psyopped into changing the Dogecoin website
> 
> I think what @qlpqlp is doing here is going to save everyone a lot of headaches. So I'm pro dealing with it - did the same in 2021 for Dogecoin Core and it helps because after the short term anger, there will be long-term peace.
> 
> > you might want to take a look at
> 
> If I were so coercible that I cared about what other people think of me, I'd not be here right now.

History cannot be rewritten—Wayback Machine and GitHub commit dates will always exist. This will only highlight that a restarted chain successfully lobbied a 60B token developer to erase a story they once proudly told, all for the purpose of promoting a shitcoin.

It’s sad to see, but I understand. If removing it from the site gives you inner peace, so be it. You’ve already done more than enough for the entire memecoin space. 🙂

**Comment by Wert112** [comment]
@patricklodder at first bells guys tryed to pump ther bags, now lucky guys trying to do the same =)

**Review by SomeoneWeird — APPROVED** [review]

**Comment by fabienghr** [comment]
The change was made in the faq but not in dogepedia yet in here
https://dogecoin.com/dogepedia/articles/dogecoin-developers/

**Pull request merged**
