### PR TITLE
resources: make blockshibe listing uniform

### PR DESCRIPTION
**Pull request by patricklodder**
Removed additional credit - unnecessary and not in line with everything else listed here.

### CODE REVIEW

**Review by xanimo — COMMENTED** [review]
My apologies since this is you removing your name but I wanted to touch base because while this does successfully remove your name from the english resources.md file it's still there for every other translation. For instance DE:

image

Thus it would need to be changed for each resources.md found in each of the following folders with exception to `en`:

image

Please let me know if you'd like to handle that in this PR or if I should ACK and submit a new issue for someone else to finish.

Thanks and apologies for misinformation!

**Comment by patricklodder** [comment]
🤣🤣🤣 

Do you ask everyone to correct your mistakes in every possible language for you? That's crazy. 

I will amend the PR, but plz, think about this process, it doesn't really make sense to ask this. ❤️

**Review by xanimo — APPROVED** [review]
ACK. I felt bad asking you to correct a mistake not of your making when you have bigger fish to fry so I've opened a PR 06aac102d amending the remaining links and yes...this process leaves much to be desired. :smile: :heart:

**Comment by qlpqlp** [comment]
> 🤣🤣🤣
> 
> Do you ask everyone to correct your mistakes in every possible language for you? That's crazy.
> 
> I will amend the PR, but plz, think about this process, it doesn't really make sense to ask this. ❤️

I will fix all outer files in a few minutes, and will merge this one :D
Much tks @patricklodder and @xanimo 
We r all in the same boat :P <3 <3 <3

**Comment by qlpqlp** [comment]
lol, did not notice that @xanimo already had submitted an PR to fix all other files :P 
https://github.com/dogecoinfoundation/dogecoin.com/pull/159

Much thanks <3<3<3

**Pull request merged**
