### PR TITLE
Add zh-TW translation

### PR DESCRIPTION
**Pull request by ukewea**
Although `zh-TW` tranlation already exists in the repo, but it only translated texts of one toml file, in this PR I translated about 70% of the content, and I'll complete the rest of them in the next stage.

### CODE REVIEW

**Comment by bobdos** [comment]
hi @ukewea 

many thanks for your contribution.

may I request you please submit files NO MORE than 5 per PR? 

as it's hard to review so many files in one PR.

**recommend 1-3 files in one PR**.

**Comment by ukewea** [comment]
Hi @bobdos,

Thanks for the comment, so I have to split this PR into 17 smaller chucks (83 files in total, 5 each PR)?

**Comment by ukewea** [comment]
There are 29 files (markdown files under `contributors` & `wallets`) which are not translated in other languages as well, can I put those files into one giant PR?

**Comment by ukewea** [comment]
@bobdos I'll first file PRs for those translated files, and could you consider my proposal of filing files that are untranslated in one PR?

Thanks.

**Pull request closed without merging**
