### PR TITLE
'How Do I Get a Wallet' Article

### PR DESCRIPTION
**Pull request by RichieJohn**
Please check links point to a valid URL. :)

### CODE REVIEW

**Review by RichieJohn — COMMENTED** [review]
This looks great to me. @tjstebbing are you able to approve this so we can merge?

**Comment by RichieJohn** [comment]
Updated article to reflect discussions with @tjstebbing and @MishaBoar

**Comment by MishaBoar** [comment]
Waiting for @tjstebbing to review this!

**Review by MishaBoar — APPROVED** [review]
This final revision seems great to me.

**Comment by RichieJohn** [comment]
Merging as per discussions for review/amendments to main if required.

**Pull request merged**
