### PR TITLE
Norwegian translation

### PR DESCRIPTION
**Pull request by DanielBoye**
Saw you had a i18n. Made a norwegian translation for it. Don't completely know if it's gonna work with the langFlags.yaml. I just saw no was commented out and don't really know if it's for this translation.

But here is an Norwegian translation.

### CODE REVIEW

**Comment by tjstebbing** [comment]
Thanks heaps Daniel, we'll pull the changes in shortly, @qlpqlp is in the process of shuffling the i18n stuff around

**Comment by DanielBoye** [comment]
Ah sounds perfect. When all the i18n is sorted out, I can translate more :) 

It would also be cool to have a «How to translate in your language» guide too, so new folkes like me knows what files that needs translations.

**Comment by qlpqlp** [comment]
> Ah sounds perfect. When all the i18n is sorted out, I can translate more :)
> 
> It would also be cool to have a «How to translate in your language» guide too, so new folkes like me knows what files that needs translations.

Can I close this PR and if you want you open a new one because there was significante changes on language structure available here?  https://github.com/dogecoinfoundation/dogecoin.com/blob/main/doc/how-to-translate-website.md

**Comment by DanielBoye** [comment]
> > Ah sounds perfect. When all the i18n is sorted out, I can translate more :)
> > It would also be cool to have a «How to translate in your language» guide too, so new folkes like me knows what files that needs translations.
> 
> Can I close this PR and if you want you open a new one because there was significante changes on language structure available here? https://github.com/dogecoinfoundation/dogecoin.com/blob/main/doc/how-to-translate-website.md

Yeah, you can. Imma just close it myself and do it in the new way as soon as possible

**Pull request closed without merging**
