### PR TITLE
First Preview dogecoin.com

### PR DESCRIPTION
**Pull request by qlpqlp**
On this release I try to integrate all CSS, fix some CSS/SCSS style problems
Changed font to Comic Sans (personally, now how Dogecoin was created, don´t make sense to change to anything besides Comic Sans, we can improve and make more professional look the Comic Sans on a webpage, maybe changing text to dark grey instead of Black color)
Changed a little the Dogepedia Style
Need opinions and also because I'm still very new to "Hugo", and how all works to get translations and files, it needs to be reviewed :)

### CODE REVIEW

**Comment by MishaBoar** [comment]
Hi, not sure what is the strategy here (@xanimo ?) - but I think you need first to rebase against master, as your commits are reverting all the Dogepedia articles and bringing them back to the old stubs before @RichieJohn and I worked on them.

**Comment by xanimo** [comment]
> Hi, not sure what is the strategy here (@xanimo ?) - but I think you need first to rebase against master, as your commits are reverting all the Dogepedia articles and bringing them back to the old stubs before @RichieJohn and I worked on them.

will follow up on this tomorrow morning but if possible to make new fork and branch of https://github.com/xanimo/dogecoin.com-1/commits/redesign and cherry-pick your commit on top of so we can merge into xanimo-redesign that would be great. i would very much like to preserve the commit history from all contributors so far and then work to integrate into main.

i suggest a fork as a way to potentially solve delays on previewing the site live as you can just git push and host at username.github.io/repo without the need for pr approval to view your work in 'production' so to speak. for instance https://xanimo.github.io/dogecoin.com-1/

more tomorrow and thanks!

**Comment by qlpqlp** [comment]
> > Hi, not sure what is the strategy here (@xanimo ?) - but I think you need first to rebase against master, as your commits are reverting all the Dogepedia articles and bringing them back to the old stubs before @RichieJohn and I worked on them.
> 
> will follow up on this tomorrow morning but if possible to make new fork and branch of https://github.com/xanimo/dogecoin.com-1/commits/redesign and cherry-pick your commit on top of so we can merge into xanimo-redesign that would be great. i would very much like to preserve the commit history from all contributors so far and then work to integrate into main.
> 
> i suggest a fork as a way to potentially solve delays on previewing the site live as you can just git push and host at username.github.io/repo without the need for pr approval to view your work in 'production' so to speak. for instance https://xanimo.github.io/dogecoin.com-1/
> 
> more tomorrow and thanks!

OK, only now I see there is something missing from my part the partials vars to be able to be translated withg the `content/*.md` files (didn't know that was working that way lol)

About the missing articles, one question, isn't better to redirect the shibe to the foundation website that alredy has the same content? exemple the FAQ/Dogepedia to not be duplicated? or we can add the FAQ and Dogepedia to dogecoin.com and redirect the Foundation FAQ and Dogepedia do dogecoin.com

**Comment by xanimo** [comment]
no i think they are useful on both sites and i think to clarify what @MishaBoar was saying is without rebasing against main, in its current state it has overwritten a lot of his and @RichieJohn work. 

this is why i propose cherry-picking on top of xanimo/dogecoin.com-1:redesign since i rebased against main last night, granted you don't overwrite the same files when resolving conflicts. this also has added benefit of .gitignore node_modules which you've included in this pr. we can then open pr with that branch against main so it will preserve contributor commits.

let me know what you are planning and if you need help with anything.

**Pull request closed without merging**
