### PR TITLE
Translation of zh-TW: part of Dogepedia

### PR DESCRIPTION
**Pull request by ukewea**
Hi, this is a series of PR for contributing zh-TW translation of Dogepedia.

### CODE REVIEW

**Comment by memetaverse** [comment]
Hi @ukewea ,
I am memetaverse, a zh-tw translation volunteer.
Thank you very much for your dogely contribution! 🙌

When I was translating I once also wondered if we need to share consistency in sentences between different version of chinese translation.
Traditional chinese and simplified chinese users can understand each other most of the time, but there are still many different characters and convention, which would be not easy to understand or not natural to readers.
The team has reached a consensus that - the best practice would still be translating from English from scratch, instead of using the other versions as reference and just replacing characters.

I was wondering if you'd be interested in continuing to help translate from scratch? There are many contents to be translated and we can divide the work. 🙂
If so we would like to keep connected with you via Discord and further help you with the git project setup for translation work.

Thanks again. Looking forward to hearing from you.

> Hi, this is a series of PR for contributing zh-TW translation of Dogepedia.

**Comment by bobdos** [comment]
agree with @memetaverse

**Comment by ukewea** [comment]
@memetaverse 當然好啊 (Sure)

So... what's the next step? should I close the series of PRs I filed earlier first?

**Comment by memetaverse** [comment]
@ukewea  woof! glad to hear😀
Would you leave us your Discord handle (e.g., memetaverse#1279 ) first?
And yes I think you can close them.
Hi @tjstebbing, I was wondering if you could help zh-tw translator ukewea get access to the repo and the discord server?🐕

> @memetaverse 當然好啊 (Sure)
> 
> So... what's the next step? should I close the series of PRs I filed earlier first?

**Comment by ukewea** [comment]
@memetaverse my Discord handle is ukewea#9417, I'm in the Dogecoin server already.😁

**Comment by memetaverse** [comment]
> 

Hi @ukewea , was trying to send you a friend request but it's forbidden haha. My discord handle is RGM#1279. 🙂
We would still need Tim's help to get you access.

**Comment by memetaverse** [comment]
Thanks to everyone. ukewea has been granted the access.

**Pull request closed without merging**
